### ISSUE TITLE
Offsets not available on leader: OffsetRange(topic: 'test', partition: 0, range: [778606 -> 778609])

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#574] opened 2018-10-10 10:37 UTC
[2018-10-10 18:36:20,266][ERROR][org.apache.spark.sql.execution.streaming.StreamExecution] Query streamExample [id = bbf1879b-4fad-4167-beb6-664876dc3699, runId = 807fb08e-2c62-4eaa-bbcc-ad2cd4e5ac6e] terminated with error
org.apache.spark.SparkException: Offsets not available on leader: OffsetRange(topic: 'test', partition: 0, range: [778606 -> 778609])
	at org.apache.spark.streaming.kafka.KafkaUtils$.org$apache$spark$streaming$kafka$KafkaUtils$$checkOffsets(KafkaUtils.scala:200)
	at org.apache.spark.streaming.kafka.KafkaUtils$$anonfun$createRDD$2.apply(KafkaUtils.scala:301)
	at org.apache.spark.streaming.kafka.KafkaUtils$$anonfun$createRDD$2.apply(KafkaUtils.scala:290)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:701)
	at org.apache.spark.streaming.kafka.KafkaUtils$.createRDD(KafkaUtils.scala:290)

**Comment by allwefantasy** [comment] 2018-10-11 01:45
Please search the article <spark streaming 玫瑰与刺> in google. Generally, it's caused by the message size. 

We will close this issue. You can reopen it or create a new one if you have any other questions.

**Closed as completed** 2018-11-14 02:57 UTC
Labels: help wanted
